Repository NightOwl888/J2N, pull requests merged in 2025-10, with the labels that each got.

#148 Upgraded xunit to 2.9.3
  .build/dependencies.props
  tests/J2N.TestUtilities/PlatformDetection.cs
  tests/Xunit/J2N.Collections.Concurrent.LurchTable.Tests/LurchTable.Tests.Concurrent.cs
  tests/Xunit/J2N.Collections.Generic.HashSet.Tests/HashSet.Generic.Tests.cs
  tests/Xunit/J2N.Collections.Generic.LinkedHashSet.Tests/LinkedHashSet.Generic.Tests.cs
  tests/Xunit/J2N.Collections.Generic.SortedSet.Tests/SortedSet.Generic.Tests.cs
  tests/Xunit/J2N.TestCommon/Collections/ICollectionTest.cs
  tests/Xunit/J2N.TestUtilities.Xunit/AssertExtensions.cs
  tests/Xunit/J2N.TestUtilities.Xunit/J2N.TestUtilities.Xunit.csproj
  tests/Xunit/J2N.TestUtilities.Xunit/compatibility/CallerArgumentExpressionAttribute.cs
Labels: notes:ignore

#149 Fixed ConditionalFactAttribute and ConditionalTheoryAttribute so the tests are conditionally skipped
  J2N.sln
  tests/Xunit/J2N.TestUtilities.Xunit.Tests/AlphabeticalOrderer.cs
  tests/Xunit/J2N.TestUtilities.Xunit.Tests/ConditionalAttributeTests.cs
  tests/Xunit/J2N.TestUtilities.Xunit.Tests/J2N.TestUtilities.Xunit.Tests.csproj
  tests/Xunit/J2N.TestUtilities.Xunit/AssertExtensions.cs
  tests/Xunit/J2N.TestUtilities.Xunit/Attributes/ConditionalFactAttribute.cs
  tests/Xunit/J2N.TestUtilities.Xunit/Attributes/ConditionalTheoryAttribute.cs
  tests/Xunit/J2N.TestUtilities.Xunit/ConditionalFactTestCase.cs
  tests/Xunit/J2N.TestUtilities.Xunit/ConditionalTheoryTestCase.cs
  tests/Xunit/J2N.TestUtilities.Xunit/Discoverers/ConditionalFactDiscoverer.cs
  tests/Xunit/J2N.TestUtilities.Xunit/Discoverers/ConditionalTestDiscoverer.cs
  tests/Xunit/J2N.TestUtilities.Xunit/Discoverers/ConditionalTheoryDiscoverer.cs
  tests/Xunit/J2N.TestUtilities.Xunit/J2N.TestUtilities.Xunit.csproj
  tests/Xunit/J2N.TestUtilities.Xunit/SkippedFactTestCase.cs
  tests/Xunit/J2N.TestUtilities.Xunit/SkippedTestCase.cs
  tests/Xunit/J2N.TestUtilities.Xunit/SkippedTestMessageBus.cs
  tests/Xunit/J2N.TestUtilities.Xunit/SkippedTheoryTestCase.cs
  tests/Xunit/J2N.TestUtilities.Xunit/compatibility/NullableAttributes.cs
Labels: notes:bug-fix

#129 Fix issue with non-hyphen negative signs in exp notation, #128
  src/J2N/Numerics/RyuDouble.cs
  src/J2N/Numerics/RyuSingle.cs
  tests/NUnit/J2N.Tests/Numerics/TestDouble.cs
  tests/NUnit/J2N.Tests/Numerics/TestSingle.cs
Labels: notes:bug-fix

#151 Broadened support for hardware intrinsics in BitOperation and MathExtensions
  Directory.Build.targets
  src/J2N/MathExtensions.cs
  src/J2N/Numerics/BitOperation.cs
  tests/J2N.TestUtilities/PlatformDetection.cs
  tests/Xunit/J2N.Runtime.Tests/Math/Double.Log2.cs
  tests/Xunit/J2N.Runtime.Tests/Math/MathTests.cs
  tests/Xunit/J2N.Runtime.Tests/Numerics/BitOperationTests.cs
Labels: notes:new-feature, notes:performance-improvement, hacktoberfest-accepted
